# Generated by Django 4.1.4 on 2023-02-04 20:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chatback', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatroom',
            options={'ordering': ['dtcreate']},
        ),
        migrations.AlterField(
            model_name='chatroom',
            name='guests',
            field=models.ManyToManyField(blank=True, related_name='whoguests', to='chatback.member', verbose_name='Members of chat'),
        ),
        migrations.AlterField(
            model_name='chatroom',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='chatback.member', verbose_name='User-creater'),
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
