# Generated by Django 4.1.4 on 2023-02-04 20:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chatback', '0004_alter_chatroom_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroom',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ownchatrooms', to='chatback.member', verbose_name='User-creater'),
        ),
    ]
