# Generated by Django 4.1.4 on 2023-02-04 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatback', '0005_alter_chatroom_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroom',
            name='guests',
            field=models.ManyToManyField(blank=True, related_name='guestinchatrooms', to='chatback.member', verbose_name='Members of chat'),
        ),
    ]
