# Generated by Django 4.1.4 on 2022-12-11 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chatback', '0003_alter_chatroom_chatmember_alter_chatroom_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroom',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chatrooms', to='chatback.member'),
        ),
        migrations.CreateModel(
            name='MemberChatroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chatroomid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chatback.chatroom')),
                ('memberid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chatback.member')),
            ],
        ),
        migrations.AddField(
            model_name='member',
            name='chats',
            field=models.ManyToManyField(related_name='member', through='chatback.MemberChatroom', to='chatback.chatroom'),
        ),
        migrations.AlterField(
            model_name='chatroom',
            name='chatmember',
            field=models.ManyToManyField(default=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chatrooms', to='chatback.member'), related_name='chatroom', through='chatback.MemberChatroom', to='chatback.member'),
        ),
    ]
