# Generated by Django 4.1.4 on 2022-12-11 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatback', '0004_alter_chatroom_creator_memberchatroom_member_chats_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroom',
            name='chatmember',
            field=models.ManyToManyField(default='creator', related_name='chatroom', through='chatback.MemberChatroom', to='chatback.member'),
        ),
    ]
