# Generated by Django 4.1.4 on 2022-12-11 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatback', '0005_alter_chatroom_chatmember'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='chats',
        ),
    ]
